/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import com.google.common.base.Stopwatch;

public class App {
    public static void main(String[] args) {
        Stopwatch timer = Stopwatch.createStarted();
        for (long seed = 1; seed <= 100000000; seed++) {
            long res = collatz(seed);
            if (seed % 1000000 == 0) {
                System.out.printf("Seed: %d Steps: %d\n", seed, res);
            }
        }

        System.out.println("Java Took " + timer.stop());
    }

    public static long collatz(long seed) {
        long cnt = 0;
        while (seed > 1) {
            cnt++;
            if (seed % 2 == 0) {
                seed /= 2;
            } else {
                seed = (seed * 3) + 1;
            }
        }

        return cnt;
    }
}
